version: '3.8'

services:
  db:
    container_name: db_mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=keycloak
    ports:
      - "3307:3307"
    volumes:
      - $DB_VOLUMES
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    environment:
      - KC_HTTP_PORT=8181
      - KEYCLOAK_ADMIN=$KC_ADMIN_USER
      - KEYCLOAK_ADMIN_PASSWORD=$KC_ADMIN_PASS
      - KC_DB=mysql
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=$DB_ROOT_PASSWORD
      - KC_DB_URL_HOST=db
      - KC_DB_URL_PORT=3307
      - KC_DB_SCHEMA=keycloak
      - KC_HTTP_RELATIVE_PATH=/auth
    ports:
      - 8181:8181
    command: start-dev
    depends_on:
      - db